# Generated by Django 3.2.6 on 2021-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=400, unique=True)),
                ('short_url', models.CharField(max_length=400, unique=True)),
            ],
        ),
    ]
